### ISSUE TITLE
win-64/libiconv-1.15-vc9_0.tar.bz2 conflicts with vc14

### ISSUE THREAD

**Issue by elfwired** [conda-forge/libiconv-feedstock#16]
```
>conda install --force -c conda-forge "libiconv>=1.15" --override-channels
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libiconv[version='>=1.15']
  - numpy -> blas==1.1=openblas -> openblas -> libflang -> *[track_features=vc14]
  - numpy -> blas==1.1=openblas -> openblas -> libflang -> vc==14
  - numpy -> python=3.6
Use "conda info <package>" to see the dependencies for each package.

```

Previous version (```libiconv-1.14-vc14_4.tar.bz2```) installs OK but is has broken ```meta.yaml```
that causes ```conda-build``` to crash
```
requirements:
    build: !!python/object/apply:builtins.getattr
        - !!python/object:conda_build.environ.Environment
            _meta: C:\Miniconda35-x64\conda-bld\recipe_1481573594901\_b_env\conda-meta
            _packages: {}
            path: C:\Miniconda35-x64\conda-bld\recipe_1481573594901\_b_env
        - package_specs
```

Maybe just rebuild ```libiconv-1.14-vc14_4.tar.bz2``` with newer ```conda-build```  installed.
